# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :build do
    match(
      app_identifier: "dev.gambit.quip",
      type: "development",
      username: "benkosten@gmail.com",
    )

    xcodebuild(
      project: "./builds/Unity-iPhone.xcodeproj",
      scheme: "UnityFramework",
      configuration: "Release",
      destination: "generic/platform=iOS",
      xcargs: "CONFIGURATION_BUILD_DIR=./ios",
      clean: true,
      build: true,
      silent: true
    )
  end
end
